# Generated by Django 5.2.16 on 2026-08-04 16:46

import django.db.models.deletion
import django.db.models.expressions
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_auditevent_action_documentsequence'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('CASH', 'Cash')], default='CASH', max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=38)),
                ('cash_received', models.DecimalField(decimal_places=2, max_digits=38)),
                ('change_given', models.DecimalField(decimal_places=2, max_digits=38)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='order',
            name='sales_order_status_valid',
        ),
        migrations.RemoveConstraint(
            model_name='order',
            name='sales_order_discard_state',
        ),
        migrations.RemoveConstraint(
            model_name='order',
            name='sales_order_discard_reason',
        ),
        migrations.AddField(
            model_name='order',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='final_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=38, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='rounding_adjustment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=38),
        ),
        migrations.AddField(
            model_name='order',
            name='rounding_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rounded_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='rounding_reason',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='order',
            name='shortage_acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('DISCARDED', 'Discarded'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=24),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['shop', 'status', '-completed_at', '-id'], name='sales_shop_completed_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'DISCARDED', 'COMPLETED'])), name='sales_order_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('order_number__isnull', False)), fields=('shop', 'order_number'), name='sales_order_shop_number_uq'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('discard_reason', ''), ('discard_was_empty', False), ('discarded_at__isnull', True), ('discarded_by__isnull', True), ('status', 'DRAFT')), models.Q(('discarded_at__isnull', False), ('discarded_by__isnull', False), ('status', 'DISCARDED')), models.Q(('discard_reason', ''), ('discard_was_empty', False), ('discarded_at__isnull', True), ('discarded_by__isnull', True), ('status', 'COMPLETED')), _connector='OR'), name='sales_order_discard_state'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'COMPLETED']), models.Q(('discard_reason', ''), ('discard_was_empty', True), ('status', 'DISCARDED'), ('subtotal', Decimal('0.00'))), models.Q(('discard_was_empty', False), ('status', 'DISCARDED'), models.Q(('discard_reason', ''), _negated=True)), _connector='OR'), name='sales_order_discard_reason'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('completed_by__isnull', True), ('final_total__isnull', True), ('order_number__isnull', True), ('rounding_adjustment', Decimal('0.00')), ('rounding_by__isnull', True), ('rounding_reason', ''), ('shortage_acknowledged', False), ('status__in', ['DRAFT', 'DISCARDED'])), models.Q(('completed_at__isnull', False), ('completed_by__isnull', False), ('final_total__isnull', False), ('order_number__isnull', False), ('status', 'COMPLETED')), _connector='OR'), name='sales_order_completion_state'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('rounding_adjustment', Decimal('0.00')), ('rounding_by__isnull', True), ('rounding_reason', '')), models.Q(models.Q(('rounding_adjustment', Decimal('0.00')), _negated=True), models.Q(('rounding_reason', ''), _negated=True), ('rounding_by__isnull', False)), _connector='OR'), name='sales_order_rounding_evidence'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('final_total__isnull', True), ('final_total__gte', 0), _connector='OR'), name='sales_order_final_total_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'DISCARDED']), ('final_total', models.ExpressionWrapper(django.db.models.expressions.CombinedExpression(models.F('subtotal'), '+', models.F('rounding_adjustment')), output_field=models.DecimalField(decimal_places=2, max_digits=38))), _connector='OR'), name='sales_order_final_total_exact'),
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='sales.order'),
        ),
        migrations.AddField(
            model_name='payment',
            name='processed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processed_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.shop'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('method', 'CASH')), name='sales_payment_cash_only'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='sales_payment_amount_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('cash_received__gte', models.F('amount'))), name='sales_payment_tender_gte_amount'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('change_given__gte', 0)), name='sales_payment_change_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('change_given', models.ExpressionWrapper(django.db.models.expressions.CombinedExpression(models.F('cash_received'), '-', models.F('amount')), output_field=models.DecimalField(decimal_places=2, max_digits=38)))), name='sales_payment_change_exact'),
        ),
    ]
