# Generated by Django 5.2.16 on 2026-08-05 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_payment_remove_order_sales_order_status_valid_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payment',
            name='sales_payment_tender_gte_amount',
        ),
        migrations.RemoveConstraint(
            model_name='payment',
            name='sales_payment_change_nonneg',
        ),
    ]
