# Generated by Django 5.2.16 on 2026-08-06 14:59

import django.db.models.deletion
import django.db.models.expressions
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_auditevent_action_and_more'),
        ('sales', '0003_remove_payment_sales_payment_tender_gte_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderVoid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=500)),
                ('request_token', models.UUIDField(default=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(max_length=32)),
                ('reason', models.CharField(max_length=500)),
                ('total_refund', models.DecimalField(decimal_places=2, max_digits=38)),
                ('request_token', models.UUIDField(default=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SalesReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveBigIntegerField()),
                ('disposition', models.CharField(choices=[('RESTOCK', 'Restock'), ('DAMAGED', 'Damaged / do not restock')], max_length=16)),
                ('unit_refund', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_refund', models.DecimalField(decimal_places=2, max_digits=38)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='order',
            name='sales_order_status_valid',
        ),
        migrations.RemoveConstraint(
            model_name='order',
            name='sales_order_discard_state',
        ),
        migrations.RemoveConstraint(
            model_name='order',
            name='sales_order_discard_reason',
        ),
        migrations.RemoveConstraint(
            model_name='order',
            name='sales_order_completion_state',
        ),
        migrations.RemoveConstraint(
            model_name='payment',
            name='sales_payment_change_exact',
        ),
        migrations.AddField(
            model_name='payment',
            name='direction',
            field=models.CharField(choices=[('RECEIPT', 'Receipt'), ('REFUND', 'Refund')], default='RECEIPT', max_length=16),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('DISCARDED', 'Discarded'), ('COMPLETED', 'Completed'), ('PARTIALLY_RETURNED', 'Partially returned'), ('RETURNED', 'Returned'), ('VOIDED', 'Voided')], default='DRAFT', max_length=24),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cash_received',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=38, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='change_given',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=38, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='sales.order'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'DISCARDED', 'COMPLETED', 'PARTIALLY_RETURNED', 'RETURNED', 'VOIDED'])), name='sales_order_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('discard_reason', ''), ('discard_was_empty', False), ('discarded_at__isnull', True), ('discarded_by__isnull', True), ('status', 'DRAFT')), models.Q(('discarded_at__isnull', False), ('discarded_by__isnull', False), ('status', 'DISCARDED')), models.Q(('discard_reason', ''), ('discard_was_empty', False), ('discarded_at__isnull', True), ('discarded_by__isnull', True), ('status__in', ['COMPLETED', 'PARTIALLY_RETURNED', 'RETURNED', 'VOIDED'])), _connector='OR'), name='sales_order_discard_state'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'COMPLETED', 'PARTIALLY_RETURNED', 'RETURNED', 'VOIDED']), models.Q(('discard_reason', ''), ('discard_was_empty', True), ('status', 'DISCARDED'), ('subtotal', Decimal('0.00'))), models.Q(('discard_was_empty', False), ('status', 'DISCARDED'), models.Q(('discard_reason', ''), _negated=True)), _connector='OR'), name='sales_order_discard_reason'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('completed_by__isnull', True), ('final_total__isnull', True), ('order_number__isnull', True), ('rounding_adjustment', Decimal('0.00')), ('rounding_by__isnull', True), ('rounding_reason', ''), ('shortage_acknowledged', False), ('status__in', ['DRAFT', 'DISCARDED'])), models.Q(('completed_at__isnull', False), ('completed_by__isnull', False), ('final_total__isnull', False), ('order_number__isnull', False), ('status__in', ['COMPLETED', 'PARTIALLY_RETURNED', 'RETURNED', 'VOIDED'])), _connector='OR'), name='sales_order_completion_state'),
        ),
        migrations.AddField(
            model_name='ordervoid',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='void', to='sales.order'),
        ),
        migrations.AddField(
            model_name='ordervoid',
            name='processed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processed_voids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordervoid',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_voids', to='core.shop'),
        ),
        migrations.AddField(
            model_name='payment',
            name='order_void',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refund_payment', to='sales.ordervoid'),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='sales.order'),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='processed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processed_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_returns', to='core.shop'),
        ),
        migrations.AddField(
            model_name='payment',
            name='sales_return',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refund_payment', to='sales.salesreturn'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('direction', 'REFUND'), models.Q(('change_given', models.ExpressionWrapper(django.db.models.expressions.CombinedExpression(models.F('cash_received'), '-', models.F('amount')), output_field=models.DecimalField(decimal_places=2, max_digits=38))), ('direction', 'RECEIPT')), _connector='OR'), name='sales_payment_change_exact'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cash_received__isnull', False), ('change_given__isnull', False), ('direction', 'RECEIPT'), ('order__isnull', False), ('order_void__isnull', True), ('sales_return__isnull', True)), models.Q(('cash_received__isnull', True), ('change_given__isnull', True), ('direction', 'REFUND'), ('order__isnull', True), ('order_void__isnull', True), ('sales_return__isnull', False)), models.Q(('cash_received__isnull', True), ('change_given__isnull', True), ('direction', 'REFUND'), ('order__isnull', True), ('order_void__isnull', False), ('sales_return__isnull', True)), _connector='OR'), name='sales_payment_source_state'),
        ),
        migrations.AddField(
            model_name='salesreturnitem',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='sales.orderitem'),
        ),
        migrations.AddField(
            model_name='salesreturnitem',
            name='sales_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='sales.salesreturn'),
        ),
        migrations.AddConstraint(
            model_name='ordervoid',
            constraint=models.UniqueConstraint(fields=('shop', 'request_token'), name='sales_void_shop_token_uq'),
        ),
        migrations.AddConstraint(
            model_name='ordervoid',
            constraint=models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='sales_void_reason_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='salesreturn',
            constraint=models.UniqueConstraint(fields=('shop', 'return_number'), name='sales_return_shop_number_uq'),
        ),
        migrations.AddConstraint(
            model_name='salesreturn',
            constraint=models.UniqueConstraint(fields=('shop', 'request_token'), name='sales_return_shop_token_uq'),
        ),
        migrations.AddConstraint(
            model_name='salesreturn',
            constraint=models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='sales_return_reason_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='salesreturn',
            constraint=models.CheckConstraint(condition=models.Q(('total_refund__gte', 0)), name='sales_return_total_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='salesreturnitem',
            constraint=models.UniqueConstraint(fields=('sales_return', 'order_item'), name='sales_return_item_line_uq'),
        ),
        migrations.AddConstraint(
            model_name='salesreturnitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='sales_return_item_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='salesreturnitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_refund__gte', 0)), name='sales_return_item_unit_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='salesreturnitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_refund__gte', 0)), name='sales_return_item_line_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='salesreturnitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_refund', models.ExpressionWrapper(django.db.models.expressions.CombinedExpression(models.F('unit_refund'), '*', models.F('quantity')), output_field=models.DecimalField(decimal_places=2, max_digits=38)))), name='sales_return_item_total_exact'),
        ),
    ]
