# Generated by Django 5.2.16 on 2026-08-03 15:38

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('currency', models.CharField(choices=[('PKR', 'Pakistani Rupee')], default='PKR', max_length=3)),
                ('timezone', models.CharField(choices=[('Asia/Karachi', 'Asia/Karachi')], default='Asia/Karachi', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('currency', 'PKR')), name='core_shop_currency_pkr'), models.CheckConstraint(condition=models.Q(('timezone', 'Asia/Karachi')), name='core_shop_timezone_karachi')],
            },
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terminals', to='core.shop')),
            ],
            options={
                'ordering': ['shop_id', 'code', 'id'],
                'constraints': [models.UniqueConstraint(fields=('shop', 'code'), name='core_terminal_shop_code_unique'), models.CheckConstraint(condition=models.Q(('code', django.db.models.functions.text.Upper('code'))), name='core_terminal_code_uppercase')],
            },
        ),
    ]
