# Generated by Django 5.2.16 on 2026-08-04 16:46

import django.db.models.deletion
from django.db import migrations, models


def create_order_sequences(apps, schema_editor):
    Shop = apps.get_model("core", "Shop")
    DocumentSequence = apps.get_model("core", "DocumentSequence")
    DocumentSequence.objects.bulk_create(
        [
            DocumentSequence(shop_id=shop_id, document_type="ORDER", next_number=1)
            for shop_id in Shop.objects.values_list("id", flat=True)
        ],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_m3_audit_vocabulary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('USER_CREATED', 'User created'), ('USER_PROFILE_UPDATED', 'User profile updated'), ('USER_ROLE_CHANGED', 'User role changed'), ('USER_ACTIVATED', 'User activated'), ('USER_DEACTIVATED', 'User deactivated'), ('USER_PASSWORD_RESET', 'User password reset'), ('USER_PASSWORD_CHANGED', 'User password changed'), ('SHOP_NAME_CHANGED', 'Shop name changed'), ('PRODUCT_PRICE_CHANGED', 'Product price changed'), ('INVENTORY_ADJUSTED', 'Inventory adjusted'), ('PRODUCT_QUICK_CREATED', 'Product quick created'), ('DRAFT_TAKEN_OVER', 'Draft taken over'), ('DRAFT_DISCARDED', 'Draft discarded'), ('ORDER_ROUNDING_APPLIED', 'Order rounding applied'), ('STOCK_SHORTAGE_ACKNOWLEDGED', 'Stock shortage acknowledged')], max_length=64),
        ),
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('ORDER', 'Order')], max_length=16)),
                ('next_number', models.PositiveBigIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_sequences', to='core.shop')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('shop', 'document_type'), name='core_sequence_shop_type_uq'), models.CheckConstraint(condition=models.Q(('next_number__gte', 1)), name='core_sequence_next_positive')],
            },
        ),
        migrations.RunPython(create_order_sequences, migrations.RunPython.noop),
    ]
