# Generated by Django 5.2.16 on 2026-08-06 14:59

from django.db import migrations, models


def create_return_sequences(apps, schema_editor):
    Shop = apps.get_model("core", "Shop")
    DocumentSequence = apps.get_model("core", "DocumentSequence")
    for shop_id in Shop.objects.values_list("id", flat=True).iterator():
        DocumentSequence.objects.get_or_create(
            shop_id=shop_id,
            document_type="RETURN",
            defaults={"next_number": 1},
        )


def remove_return_sequences(apps, schema_editor):
    DocumentSequence = apps.get_model("core", "DocumentSequence")
    DocumentSequence.objects.filter(document_type="RETURN").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_auditevent_action_documentsequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('USER_CREATED', 'User created'), ('USER_PROFILE_UPDATED', 'User profile updated'), ('USER_ROLE_CHANGED', 'User role changed'), ('USER_ACTIVATED', 'User activated'), ('USER_DEACTIVATED', 'User deactivated'), ('USER_PASSWORD_RESET', 'User password reset'), ('USER_PASSWORD_CHANGED', 'User password changed'), ('SHOP_NAME_CHANGED', 'Shop name changed'), ('PRODUCT_PRICE_CHANGED', 'Product price changed'), ('INVENTORY_ADJUSTED', 'Inventory adjusted'), ('PRODUCT_QUICK_CREATED', 'Product quick created'), ('DRAFT_TAKEN_OVER', 'Draft taken over'), ('DRAFT_DISCARDED', 'Draft discarded'), ('ORDER_ROUNDING_APPLIED', 'Order rounding applied'), ('STOCK_SHORTAGE_ACKNOWLEDGED', 'Stock shortage acknowledged'), ('ORDER_RETURNED', 'Order returned'), ('ORDER_VOIDED', 'Order voided')], max_length=64),
        ),
        migrations.AlterField(
            model_name='documentsequence',
            name='document_type',
            field=models.CharField(choices=[('ORDER', 'Order'), ('RETURN', 'Return')], max_length=16),
        ),
        migrations.RunPython(create_return_sequences, remove_return_sequences),
    ]
