# Generated by Django 5.2.16 on 2026-08-03 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0003_alter_auditevent_action_alter_auditevent_target_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('RECEIPT', 'Receipt'), ('ADJUSTMENT', 'Adjustment'), ('SALE', 'Sale'), ('RETURN', 'Return'), ('VOID', 'Void')], max_length=16)),
                ('quantity_change', models.BigIntegerField()),
                ('balance_after', models.BigIntegerField()),
                ('reason', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='catalog.product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='core.shop')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['shop', '-created_at'], name='inventory_shop_created_idx'), models.Index(fields=['product', '-created_at'], name='inventory_product_created_idx'), models.Index(fields=['shop', 'movement_type', '-created_at'], name='inventory_shop_type_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity_change', 0), _negated=True), name='inventory_quantity_not_zero'), models.CheckConstraint(condition=models.Q(models.Q(('movement_type', 'RECEIPT'), _negated=True), ('quantity_change__gt', 0), _connector='OR'), name='inventory_receipt_positive'), models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='inventory_reason_not_empty')],
            },
        ),
    ]
