# Generated by Django 5.2.16 on 2026-08-04 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0005_alter_auditevent_action_documentsequence'),
        ('inventory', '0001_initial'),
        ('sales', '0002_payment_remove_order_sales_order_status_valid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_movements', to='sales.orderitem'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('movement_type', 'SALE'), ('order_item__isnull', False), ('quantity_change__lt', 0)), models.Q(models.Q(('movement_type', 'SALE'), _negated=True), ('order_item__isnull', True)), _connector='OR'), name='inventory_sale_source_state'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovement',
            constraint=models.UniqueConstraint(condition=models.Q(('movement_type', 'SALE')), fields=('order_item',), name='inventory_sale_order_item_uq'),
        ),
    ]
