# Generated by Django 5.2.16 on 2026-08-06 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0006_alter_auditevent_action_and_more'),
        ('inventory', '0002_inventorymovement_order_item_and_more'),
        ('sales', '0004_ordervoid_salesreturn_salesreturnitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='order_void',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='sales.ordervoid'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='return_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movement', to='sales.salesreturnitem'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='voided_order_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='void_movement', to='sales.orderitem'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('movement_type', 'RETURN'), ('order_item__isnull', True), ('order_void__isnull', True), ('quantity_change__gt', 0), ('return_item__isnull', False), ('voided_order_item__isnull', True)), models.Q(('movement_type', 'VOID'), ('order_item__isnull', True), ('order_void__isnull', False), ('quantity_change__gt', 0), ('return_item__isnull', True), ('voided_order_item__isnull', False)), models.Q(('movement_type', 'SALE'), ('order_item__isnull', False), ('order_void__isnull', True), ('quantity_change__lt', 0), ('return_item__isnull', True), ('voided_order_item__isnull', True)), models.Q(('movement_type__in', ['RECEIPT', 'ADJUSTMENT']), ('order_item__isnull', True), ('order_void__isnull', True), ('return_item__isnull', True), ('voided_order_item__isnull', True)), _connector='OR'), name='inventory_movement_source_shape'),
        ),
    ]
