# Generated by Django 5.2.16 on 2026-08-03 17:18

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_auditevent_action_alter_auditevent_target_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(blank=True, max_length=64, null=True)),
                ('sku', models.CharField(blank=True, max_length=64, null=True)),
                ('name', models.CharField(max_length=200)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stock_on_hand', models.BigIntegerField(default=0)),
                ('creation_source', models.CharField(choices=[('CATALOG', 'Catalog'), ('POS_QUICK_CREATE', 'POS quick create')], default='CATALOG', max_length=24)),
                ('needs_review', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_products', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='core.shop')),
            ],
            options={
                'indexes': [models.Index(fields=['shop', 'barcode'], name='catalog_shop_barcode_idx'), models.Index(fields=['shop', 'is_active', 'name'], name='catalog_shop_active_name_idx'), models.Index(fields=['shop', 'needs_review'], name='catalog_shop_review_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('barcode__isnull', False)), fields=('shop', 'barcode'), name='catalog_barcode_unique'), models.UniqueConstraint(models.F('shop'), django.db.models.functions.text.Lower('sku'), condition=models.Q(('sku__isnull', False)), name='catalog_sku_ci_unique'), models.CheckConstraint(condition=models.Q(('selling_price__gte', 0)), name='catalog_selling_price_gte_0'), models.CheckConstraint(condition=models.Q(('cost_price__isnull', True), ('cost_price__gte', 0), _connector='OR'), name='catalog_cost_price_gte_0'), models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='catalog_name_not_empty')],
            },
        ),
    ]
